services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    entrypoint: wait-for database:3306 -t 40 -- ./start.sh
    depends_on:
      - database
    networks:
      - fiapnetwork
      
  database:
    image: mysql:8.0.36
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    networks:
      - fiapnetwork

networks:
  fiapnetwork:
    driver: bridge

      